In [1]:
import pandas as pd

from src.prediction import predict_fraud

df = pd.read_csv("insurance_claims.csv")

result = predict_fraud(df.iloc[:10])

result

   fraud_probability  prediction risk_level    decision
0           0.739200           1      Élevé      Fraude
1           0.158509           0     Faible  Non fraude
2           0.116716           0     Faible  Non fraude
3           0.898010           1      Élevé      Fraude
4           0.093279           0     Faible  Non fraude
5           0.869292           1      Élevé      Fraude
6           0.088470           0     Faible  Non fraude
7           0.157082           0     Faible  Non fraude
8           0.068277           0     Faible  Non fraude
9           0.091459           0     Faible  Non fraude

In [2]:
result = predict_fraud(df.iloc[:20])

result

    fraud_probability  prediction risk_level    decision
0            0.739200           1      Élevé      Fraude
1            0.158509           0     Faible  Non fraude
2            0.116716           0     Faible  Non fraude
3            0.898010           1      Élevé      Fraude
4            0.093279           0     Faible  Non fraude
5            0.869292           1      Élevé      Fraude
6            0.088470           0     Faible  Non fraude
7            0.157082           0     Faible  Non fraude
8            0.068277           0     Faible  Non fraude
9            0.091459           0     Faible  Non fraude
10           0.112091           0     Faible  Non fraude
11           0.777931           1      Élevé      Fraude
12           0.108627           0     Faible  Non fraude
13           0.088252           0     Faible  Non fraude
14           0.178846           0     Faible  Non fraude
15           0.736854           1      Élevé      Fraude
16           0.714970           1      Élevé      Fraude
17           0.071331           0     Faible  Non fraude
18           0.127500           0     Faible  Non fraude
19           0.668385           1      Élevé      Fraude

In [3]:
result["decision"].value_counts()

decision
Non fraude    13
Fraude         7
Name: count, dtype: int64

In [4]:
result["risk_level"].value_counts()

risk_level
Faible    13
Élevé      7
Name: count, dtype: int64

In [5]:
result.sort_values(
    "fraud_probability",
    ascending=False
).head(10)

    fraud_probability  prediction risk_level    decision
3            0.898010           1      Élevé      Fraude
5            0.869292           1      Élevé      Fraude
11           0.777931           1      Élevé      Fraude
0            0.739200           1      Élevé      Fraude
15           0.736854           1      Élevé      Fraude
16           0.714970           1      Élevé      Fraude
19           0.668385           1      Élevé      Fraude
14           0.178846           0     Faible  Non fraude
1            0.158509           0     Faible  Non fraude
7            0.157082           0     Faible  Non fraude